/* eslint-disable prettier/prettier */
const users = [
    {
      id: '1',
      backgroundUrl: 'https://images.pexels.com/photos/6039868/pexels-photo-6039868.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load',
      photoUrl: 'https://images.pexels.com/photos/7500307/pexels-photo-7500307.jpeg?auto=compress&cs=tinysrgb&w=800&lazy=load',
      isProMember: true,
      isFollowing : true,
      isMessageAllowed: true,
      numberOfFollowers: '2,500',
      description: 'Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document',
      name: 'Enpacto Tech',
      category: 'IT Services',
      location: 'Valsad',
    },
    {
        id: '2',
        backgroundUrl: 'https://images.pexels.com/photos/984858/pexels-photo-984858.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load',
        photoUrl: 'https://images.pexels.com/photos/7153908/pexels-photo-7153908.jpeg?auto=compress&cs=tinysrgb&w=800&lazy=load',
        isProMember: true,
        isFollowing : false,
        isMessageAllowed: true,
        numberOfFollowers: '2,500',
        description: 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document',
        name: 'Homespace Creations',
        category: 'Interior & Exterior',
        location: 'Silvasa',
      },
      {
        id: '3',
        backgroundUrl: 'https://images.pexels.com/photos/6039868/pexels-photo-6039868.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load',
        photoUrl: 'https://images.pexels.com/photos/7500307/pexels-photo-7500307.jpeg?auto=compress&cs=tinysrgb&w=800&lazy=load',
        isProMember: false,
        isFollowing : true,
        isMessageAllowed: false,
        numberOfFollowers: '2,500',
        description: 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document',
        name: 'Hikivison Camera Services',
        category: 'Photography & CCTV',
        location: 'Daman',
      },
      {
        id: '4',
        backgroundUrl: 'https://images.pexels.com/photos/6039868/pexels-photo-6039868.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load',
        photoUrl: 'https://images.pexels.com/photos/7500307/pexels-photo-7500307.jpeg?auto=compress&cs=tinysrgb&w=800&lazy=load',
        isProMember: false,
        isFollowing : false,
        isMessageAllowed: true,
        numberOfFollowers: '2,500',
        description: 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document',
        name: 'Annapurna Restaurant',
        category: 'Hotel & Restaurant',
        location: 'Vapi',
      },
      {
        id: '5',
        backgroundUrl: 'https://images.pexels.com/photos/3968051/pexels-photo-3968051.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load',
        photoUrl: 'https://images.pexels.com/photos/7500307/pexels-photo-7500307.jpeg?auto=compress&cs=tinysrgb&w=800&lazy=load',
        isProMember: true,
        isFollowing : false,
        isMessageAllowed: false,
        numberOfFollowers: '2,500',
        description: 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document',
        name: 'TechnoMart',
        category: 'Electronics Showroom',
        location: 'Vapi',
      },

];

export default users;
