/* eslint-disable prettier/prettier */
const users = [
    {
      id: '1',
      photoUrl: 'https://images.pexels.com/photos/7500307/pexels-photo-7500307.jpeg?auto=compress&cs=tinysrgb&w=800&lazy=load',
      isProMember: true,
      isFollowing : true,
      isWhatsAppMessageAllowed: true,
      isMessageAllowed: true,
      numberOfFollowers: '2,500',
      description: 'Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document',
      name: 'Krishna Kumar',
      category: 'Interior Designer',
      location: 'Valsad',
    },
    {
        id: '2',
        photoUrl: 'https://images.pexels.com/photos/7153908/pexels-photo-7153908.jpeg?auto=compress&cs=tinysrgb&w=800&lazy=load',
        isProMember: true,
        isFollowing : false,
        isWhatsAppMessageAllowed: false,
        isMessageAllowed: true,
        numberOfFollowers: '2,500',
        description: 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document',
        name: 'Satyam Dubey',
        category: 'Mechanic',
        location: 'Silvasa',
      },
      {
        id: '3',
        photoUrl: 'https://images.pexels.com/photos/7500307/pexels-photo-7500307.jpeg?auto=compress&cs=tinysrgb&w=800&lazy=load',
        isProMember: false,
        isFollowing : true,
        isWhatsAppMessageAllowed: false,
        isMessageAllowed: false,
        numberOfFollowers: '2,500',
        description: 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document',
        name: 'Bittu Thakur',
        category: 'Carpentry & Welding',
        location: 'Daman',
      },
      {
        id: '4',
        photoUrl: 'https://images.pexels.com/photos/7500307/pexels-photo-7500307.jpeg?auto=compress&cs=tinysrgb&w=800&lazy=load',
        isProMember: false,
        isFollowing : false,
        isWhatsAppMessageAllowed: true,
        isMessageAllowed: true,
        numberOfFollowers: '2,500',
        description: 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document',
        name: 'Shivani Zutshi',
        category: 'Beautician (Company)',
        location: 'Vapi',
      },
      {
        id: '5',
        photoUrl: 'https://images.pexels.com/photos/7500307/pexels-photo-7500307.jpeg?auto=compress&cs=tinysrgb&w=800&lazy=load',
        isProMember: true,
        isFollowing : false,
        isWhatsAppMessageAllowed: true,
        isMessageAllowed: false,
        numberOfFollowers: '2,500',
        description: 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document',
        name: 'Jitendra Sahoo',
        category: 'Plumber (Company)',
        location: 'Vapi',
      },

];

export default users;
